version: '3.0'

services:

  php:
    volumes:
      - '.:/var/www/html'
    build:
      context: .
      dockerfile: docker/php/Dockerfile
  nginx:

    environment:
        - NGINX_PORT=80
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - '.:/var/www/html'
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile