version: '3.4'

services:
  php:
    networks:
      - web
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  nginx:
    networks:
      - web
    environment:
      - NGINX_PORT=80
    ports:
      - "8080:80"

networks:
  web: