version: '3.4'

services:
  php:
    volumes:
      - '.:/var/www/html'
    image: php:8-fpm-alpine3.16
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - '.:/var/www/html'

networks:
  web: