version: '3.4'

services:
  php:
    volumes:
      - '.:/var/www/html'
    image: app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - '.:/var/www/html'

networks:
  web: